package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// The one endpoint the daemon talks to. The single place the rule group and the
// client agree on it.
const (
	usageHost = "api.anthropic.com"
	usagePort = "443"

	// subscriptionURL is stable across releases: GitHub resolves latest/download
	// to the newest release's asset, so a subscriber picks up each release's
	// paths without touching the subscription.
	subscriptionURL = "https://github.com/tedwardd/tmux-claude-monitor/releases/latest/download/claude-monitor.lsrules"
)

// homebrewPrefixes covers Apple Silicon and Intel. A cask install is reachable
// both through the fixed bin symlink and the versioned Caskroom directory it
// resolves to, and Little Snitch matches the full executable path with no
// wildcard support, so the published group names all of them.
var homebrewPrefixes = []string{"/opt/homebrew", "/usr/local"}

// denyPolicy controls whether the group also forbids everything else.
type denyPolicy int

const (
	denyOmit denyPolicy = iota
	denyDisabled
	denyEnabled
)

type lsRule struct {
	Action      string `json:"action"`
	Process     string `json:"process"`
	Direction   string `json:"direction"`
	Protocol    string `json:"protocol,omitempty"`
	Ports       string `json:"ports,omitempty"`
	RemoteHosts string `json:"remote-hosts,omitempty"`
	Remote      string `json:"remote,omitempty"`
	Disabled    bool   `json:"disabled,omitempty"`
	Notes       string `json:"notes,omitempty"`
}

type lsGroup struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Rules       []lsRule `json:"rules"`
}

// releasePaths returns the install locations a published group has to cover for
// the given release. All of them are deterministic, so the file needs no
// knowledge of the machine it will be used on.
func releasePaths(version string) []string {
	version = strings.TrimPrefix(version, "v")
	paths := make([]string, 0, len(homebrewPrefixes)*2)
	for _, prefix := range homebrewPrefixes {
		paths = append(paths, prefix+"/bin/claude-monitor")
		paths = append(paths, fmt.Sprintf("%s/Caskroom/claude-monitor/%s/claude-monitor", prefix, version))
	}
	return paths
}

// executablePaths returns the paths the running binary can legitimately be
// identified by, most stable first.
func executablePaths() ([]string, error) {
	exe, err := os.Executable()
	if err != nil {
		return nil, err
	}
	resolved, err := filepath.EvalSymlinks(exe)
	if err != nil {
		resolved = exe
	}

	paths := []string{resolved}
	if linked, err := exec.LookPath(filepath.Base(resolved)); err == nil {
		if abs, err := filepath.Abs(linked); err == nil && abs != resolved {
			if same, err := filepath.EvalSymlinks(abs); err == nil && same == resolved {
				paths = append([]string{abs}, paths...)
			}
		}
	}
	return paths, nil
}

func buildLSGroup(description string, paths []string, deny denyPolicy) lsGroup {
	g := lsGroup{Name: "claude-monitor", Description: description}

	for _, p := range paths {
		g.Rules = append(g.Rules, lsRule{
			Action:      "allow",
			Process:     p,
			Direction:   "outgoing",
			Protocol:    "tcp",
			Ports:       usagePort,
			RemoteHosts: usageHost,
			Notes: "GET https://" + usageHost + "/api/oauth/usage. Sent once per poll " +
				"interval (5 minutes by default), on `claude-monitor refresh`, and on wake " +
				"from sleep. The only connection the daemon opens.",
		})
	}

	if deny == denyOmit {
		return g
	}

	notes := "Nothing else is needed, so denying the rest makes the allow rules above " +
		"an enforceable boundary rather than a description."
	if deny == denyDisabled {
		notes += " Disabled by default: regenerate with --strict, or enable it here, once " +
			"you are satisfied the allow rules cover your setup."
	}
	for _, p := range paths {
		g.Rules = append(g.Rules, lsRule{
			Action:    "deny",
			Process:   p,
			Direction: "outgoing",
			Remote:    "any",
			Disabled:  deny == denyDisabled,
			Notes:     notes,
		})
	}
	return g
}

const localDescription = "Every outbound connection claude-monitor makes, for this " +
	"install. The daemon contacts one endpoint, the Anthropic OAuth usage API, and " +
	"nothing else. Generated by `claude-monitor lsrules`, so the rules name this " +
	"binary rather than granting access to anything else on the machine."

func releaseDescription(version string) string {
	return "Every outbound connection claude-monitor makes. The daemon contacts one " +
		"endpoint, the Anthropic OAuth usage API, and nothing else. Covers the Homebrew " +
		"install paths for version " + strings.TrimPrefix(version, "v") + " on both Apple " +
		"Silicon and Intel. Subscribe to this group rather than importing it and Little " +
		"Snitch will follow each release's paths on its own."
}

// subscribeURI is the handler Little Snitch registers for adding a rule group
// subscription, so the user does not have to paste the URL by hand.
func subscribeURI() string {
	return "x-littlesnitch:subscribe-rules?url=" + url.QueryEscape(subscriptionURL)
}

func runLSRules() {
	var (
		strict      bool
		subscribe   bool
		relVersion  string
		unknownArgs []string
	)
	args := os.Args[2:]
	for i := 0; i < len(args); i++ {
		switch {
		case args[i] == "--strict":
			strict = true
		case args[i] == "--subscribe":
			subscribe = true
		case args[i] == "--release" && i+1 < len(args):
			i++
			relVersion = args[i]
		case strings.HasPrefix(args[i], "--release="):
			relVersion = strings.TrimPrefix(args[i], "--release=")
		default:
			unknownArgs = append(unknownArgs, args[i])
		}
	}
	if len(unknownArgs) > 0 {
		fmt.Fprintf(os.Stderr, "lsrules: unknown argument %q\n", unknownArgs[0])
		os.Exit(1)
	}

	if subscribe {
		uri := subscribeURI()
		if out, err := exec.Command("open", uri).CombinedOutput(); err != nil {
			fmt.Fprintf(os.Stderr, "lsrules: open %s: %v: %s\n", uri, err, strings.TrimSpace(string(out)))
			fmt.Fprintf(os.Stderr, "Subscribe manually in Little Snitch with this URL:\n  %s\n", subscriptionURL)
			os.Exit(1)
		}
		fmt.Printf("Asked Little Snitch to subscribe to:\n  %s\n", subscriptionURL)
		return
	}

	var g lsGroup
	if relVersion != "" {
		// The published group is deliberately allow-only. A subscription that
		// silently denied traffic would be a poor surprise, so enforcement stays a
		// local, deliberate choice via --strict.
		g = buildLSGroup(releaseDescription(relVersion), releasePaths(relVersion), denyOmit)
	} else {
		paths, err := executablePaths()
		if err != nil {
			fmt.Fprintf(os.Stderr, "lsrules: locate executable: %v\n", err)
			os.Exit(1)
		}
		deny := denyDisabled
		if strict {
			deny = denyEnabled
		}
		g = buildLSGroup(localDescription, paths, deny)
	}

	data, err := json.MarshalIndent(g, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "lsrules: %v\n", err)
		os.Exit(1)
	}
	fmt.Println(string(data))
}
