package cmd

import (
	"encoding/json"
	"fmt"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// The one endpoint the daemon talks to. The single place the rule group and the
// client agree on it.
const (
	usageHost = "api.anthropic.com"
	usagePort = "443"

	// subscriptionURL is stable across releases: GitHub resolves latest/download
	// to the newest release's asset, so a subscriber picks up each release's
	// paths without touching the subscription.
	subscriptionURL = "https://github.com/tedwardd/tmux-claude-monitor/releases/latest/download/claude-monitor.lsrules"
)

// homebrewPrefixes covers Apple Silicon and Intel. A cask install is reachable
// both through the fixed bin symlink and the versioned Caskroom directory it
// resolves to, so the group names both.
var homebrewPrefixes = []string{"/opt/homebrew", "/usr/local"}

// denyPolicy controls whether the group also forbids everything else.
type denyPolicy int

const (
	denyOmit denyPolicy = iota
	denyDisabled
	denyEnabled
)

type lsRule struct {
	Action    string `json:"action"`
	Process   string `json:"process"`
	Direction string `json:"direction"`
	Protocol  string `json:"protocol,omitempty"`
	Ports     string `json:"ports,omitempty"`
	// remote-domains, not remote-hosts. A host rule needs Little Snitch to have
	// tied the name to the connection for this process, but the daemon resolves
	// through the system resolver so the lookup belongs to mDNSResponder, and the
	// rule never matches. Little Snitch's own generated rules use domains.
	RemoteDomains string `json:"remote-domains,omitempty"`
	Remote        string `json:"remote,omitempty"`
	Disabled      bool   `json:"disabled,omitempty"`
	Notes         string `json:"notes,omitempty"`
}

type lsGroup struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Rules       []lsRule `json:"rules"`
}

// releasePaths returns the install locations a published group has to cover.
// The Caskroom directory is named after the version, so it is wildcarded: Little
// Snitch accepts a * in a process path, as its own alert-generated rules do, and
// that keeps the group correct across upgrades without naming a version.
func releasePaths() []string {
	paths := make([]string, 0, len(homebrewPrefixes)*2)
	for _, prefix := range homebrewPrefixes {
		paths = append(paths, prefix+"/bin/claude-monitor")
		paths = append(paths, prefix+"/Caskroom/claude-monitor/*/claude-monitor")
	}
	return paths
}

// executablePaths returns the paths the running binary can legitimately be
// identified by, most stable first.
func executablePaths() ([]string, error) {
	exe, err := os.Executable()
	if err != nil {
		return nil, err
	}
	resolved, err := filepath.EvalSymlinks(exe)
	if err != nil {
		resolved = exe
	}

	paths := []string{resolved}
	if linked, err := exec.LookPath(filepath.Base(resolved)); err == nil {
		if abs, err := filepath.Abs(linked); err == nil && abs != resolved {
			if same, err := filepath.EvalSymlinks(abs); err == nil && same == resolved {
				paths = append([]string{abs}, paths...)
			}
		}
	}
	return paths, nil
}

func buildLSGroup(description string, paths []string, deny denyPolicy) lsGroup {
	g := lsGroup{Name: "claude-monitor", Description: description}

	for _, p := range paths {
		g.Rules = append(g.Rules, lsRule{
			Action:        "allow",
			Process:       p,
			Direction:     "outgoing",
			Protocol:      "tcp",
			Ports:         usagePort,
			RemoteDomains: usageHost,
			Notes: "GET https://" + usageHost + "/api/oauth/usage. Sent once per poll " +
				"interval (5 minutes by default), on `claude-monitor refresh`, and on wake " +
				"from sleep. The only connection the daemon opens.",
		})
	}

	if deny == denyOmit {
		return g
	}

	notes := "Nothing else is needed, so denying the rest makes the allow rules above " +
		"an enforceable boundary rather than a description."
	if deny == denyDisabled {
		notes += " Disabled by default: regenerate with --strict, or enable it here, once " +
			"you are satisfied the allow rules cover your setup."
	}
	for _, p := range paths {
		g.Rules = append(g.Rules, lsRule{
			Action:    "deny",
			Process:   p,
			Direction: "outgoing",
			Remote:    "any",
			Disabled:  deny == denyDisabled,
			Notes:     notes,
		})
	}
	return g
}

const localDescription = "Every outbound connection claude-monitor makes, for this " +
	"install. The daemon contacts one endpoint, the Anthropic OAuth usage API, and " +
	"nothing else. Generated by `claude-monitor lsrules`, so the rules name this " +
	"binary rather than granting access to anything else on the machine."

func releaseDescription(version string) string {
	return "Every outbound connection claude-monitor makes. The daemon contacts one " +
		"endpoint, the Anthropic OAuth usage API, and nothing else. Covers the Homebrew " +
		"install paths on both Apple Silicon and Intel, with the version directory " +
		"wildcarded so the rules survive upgrades. Published with " +
		strings.TrimPrefix(version, "v") + "."
}

// subscribeURI is the handler Little Snitch registers for adding a rule group
// subscription, so the user does not have to paste the URL by hand.
func subscribeURI() string {
	return "x-littlesnitch:subscribe-rules?url=" + url.QueryEscape(subscriptionURL)
}

// lsRulesExplanation is what a bare `lsrules` prints. Adding a firewall
// subscription is not something to do as a side effect of someone looking at a
// command, so nothing happens until they ask for it.
const lsRulesExplanation = `Little Snitch integration for claude-monitor.

Nothing on your system changes unless you pass --subscribe.

With --subscribe, Little Snitch is asked to add a rule group subscription for:

  %s

Little Snitch shows its own confirmation before anything is added, and you can
read the rules first with:

  curl -fsSL %s

What the group contains, for both the /opt/homebrew and /usr/local prefixes:

  allow  <prefix>/bin/claude-monitor                          -> %s:%s
  allow  <prefix>/Caskroom/claude-monitor/*/claude-monitor    -> %s:%s

That is the whole list. It lets this program reach one domain, the usage API the
daemon polls, and grants nothing to any other program. There are no deny rules.

The version directory is wildcarded, so the rules keep matching after an upgrade
rather than needing re-approval. A subscription rather than a one-off import so
that any later correction reaches you too.

Options:
  --subscribe, --add    ask Little Snitch to add the subscription
  --print               print a rule group for this install instead of subscribing
  --print --strict      ... and include deny rules for everything else
`

type lsRulesArgs struct {
	strict     bool
	subscribe  bool
	printGroup bool
	release    string
	unknown    []string
}

func parseLSRulesArgs(args []string) lsRulesArgs {
	var a lsRulesArgs
	for i := 0; i < len(args); i++ {
		switch {
		case args[i] == "--strict":
			a.strict = true
		case args[i] == "--subscribe", args[i] == "--add":
			a.subscribe = true
		case args[i] == "--print":
			a.printGroup = true
		case args[i] == "--release" && i+1 < len(args):
			i++
			a.release = args[i]
		case strings.HasPrefix(args[i], "--release="):
			a.release = strings.TrimPrefix(args[i], "--release=")
		default:
			a.unknown = append(a.unknown, args[i])
		}
	}
	return a
}

func runLSRules() {
	a := parseLSRulesArgs(os.Args[2:])
	if len(a.unknown) > 0 {
		fmt.Fprintf(os.Stderr, "lsrules: unknown argument %q\n", a.unknown[0])
		os.Exit(1)
	}
	strict, subscribe, printGroup, relVersion := a.strict, a.subscribe, a.printGroup, a.release

	switch {
	case subscribe:
		runLSSubscribe()
	case relVersion != "":
		// The published group is deliberately allow-only. A subscription that
		// silently denied traffic would be a poor surprise, so enforcement stays a
		// local, deliberate choice via --strict.
		printLSGroup(buildLSGroup(releaseDescription(relVersion), releasePaths(), denyOmit))
	case printGroup || strict:
		paths, err := executablePaths()
		if err != nil {
			fmt.Fprintf(os.Stderr, "lsrules: locate executable: %v\n", err)
			os.Exit(1)
		}
		deny := denyDisabled
		if strict {
			deny = denyEnabled
		}
		printLSGroup(buildLSGroup(localDescription, paths, deny))
	default:
		fmt.Printf(lsRulesExplanation,
			subscriptionURL, subscriptionURL,
			usageHost, usagePort, usageHost, usagePort)
	}
}

func runLSSubscribe() {
	uri := subscribeURI()
	out, err := exec.Command("open", uri).CombinedOutput()
	if err != nil {
		fmt.Fprintf(os.Stderr, "lsrules: open %s: %v: %s\n", uri, err, strings.TrimSpace(string(out)))
		fmt.Fprintf(os.Stderr, "Add the subscription in Little Snitch by hand instead:\n  %s\n", subscriptionURL)
		os.Exit(1)
	}
	fmt.Printf("Handed Little Snitch this subscription URL:\n  %s\n\n"+
		"Confirm it in the window Little Snitch opens. Nothing is added until you do.\n",
		subscriptionURL)
}

func printLSGroup(g lsGroup) {
	data, err := json.MarshalIndent(g, "", "  ")
	if err != nil {
		fmt.Fprintf(os.Stderr, "lsrules: %v\n", err)
		os.Exit(1)
	}
	fmt.Println(string(data))
}
